export const HOME = '/'
export const GALLERY = '/gallery'
export const MATERIALS = '/materials'
export const ABOUT_US = '/about-us'
export const FOR_PARTNERS = '/for-partners'
export const SHOPPING_CART = '/shopping-cart'
export const CONFIGURATOR = '/configurator'
export const ESHOP = '/e-shop'
