export const NODE_MAILER_SERVICE = process.env.NEXT_PUBLIC_NODE_MAILER_SERVICE!
export const NODE_MAILER_HOST = process.env.NEXT_PUBLIC_NODE_MAILER_HOST!
export const NODE_MAILER_SECURE = process.env.NEXT_PUBLIC_NODE_MAILER_SECURE!
export const NODE_MAILER_PORT = process.env.NEXT_PUBLIC_NODE_MAILER_PORT!
export const NODE_MAILER_USER = process.env.NEXT_PUBLIC_NODE_MAILER_USER!
export const NODE_MAILER_PASSWORD = process.env.NEXT_PUBLIC_NODE_MAILER_PASSWORD!