version: '3.8'
services:
  mongodb:
    image: mongo:5.0.0
    container_name: mongodb
    command: mongod --wiredTigerCacheSizeGB 1 --oplogSize 128 --replSet rs0
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
    #   MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    # ports:
    #   - '27017:27017'
    networks:
      - server-network
    volumes:
      - ./backend_data:/data/db
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
  mongo-init-replica:
    image: mongo:5.0.0
    container_name: mono-init-replica
    command: >
      bash -c
        "for i in `seq 1 30`; do
          mongo mongodb/admin --eval \"
            rs.initiate({
              _id: 'rs0',
              members: [ { _id: 0, host: 'localhost:27017' } ]})\" &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s)"
    depends_on:
      - mongodb
    networks:
      - server-network
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
  mongo-express:
    image: mongo-express
    container_name: server-mongo-express
    environment:
      # ME_CONFIG_MONGODB_SERVER: ${MONGODB_SERVER}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: ${MONGODB_ENABLE_ADMIN}
      # ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_ADMINUSERNAME}
      # ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_ADMINPASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGODB_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGODB_BASICAUTH_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - server-network
    ports:
      - 8081:8081
    healthcheck:
      test: wget --quiet --tries=3 --spider http://admin:heslo@localhost:8081 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1m"


volumes:
  backend_data:

networks:
  server-network:
    driver: bridge