apiVersion: v1
kind: Pod
metadata:
  name: private-reg
  labels:
    name: private-reg
spec:
  containers:
  - name: private-reg-container
    image: dominiksecka/waller:waller_be_test
  imagePullSecrets:
  - name: regcred