export enum LovepixEvent {
  UPLOAD_IMAGE_LANDING_PAGE = 'upload_image_landing_page',
  UPLOAD_IMAGE_CONFIGURATOR = 'upload_image_configurator',
  UPLOAD_IMAGE_DRAG_AND_DROP_LANDING_PAGE = 'upload_image_drag_and_drop_landing_page',
  UPLOAD_IMAGE_DRAG_AND_DROP_CONFIGURATOR = 'upload_image_drag_and_drop_configurator',
  SELECT_DIMENSION = 'select_dimension',
  SELECT_MATERIAL = 'select_material',
  REMOVE_IMAGE_FROM_CONFIGURATOR = 'remove_image',
  ADD_TO_CART_CONFIGURATOR = 'add_to_cart_configurator',
  ADD_TO_CART_ESHOP_PRODUCT = 'add_to_cart_eshop_product',
  SUBMIT_ORDER = 'submit_order',
  SELECT_DELIVERY = 'select_delivery',
  SELECT_PAYMENT = 'select_payment',
  ADD_COUPON = 'add_coupon',
  ORDER_VALIDATION = 'order_validation',
  NOTIFICATION_EMAILS = 'notification_emails',
  FIREBASE_IMAGE_UPLOAD = 'firebase_image_upload',
}
