import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import ResponsiveAppBar from '../src/app-bar/responsive-app-bar'
import { GetStaticProps } from 'next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import CustomForPartners from '../src/screens-content/for-partners/for-partners'
import FooterLayout from "../src/screens-content/footer/footer";
import MetaTags from 'meta-tags/meta'

const ForPartners: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>For Partners</title>
        <meta name='For Partners' content='Generated by create next app' />
      </Head>

      {/* MetaTags has to be executed outside of head*/}
      <MetaTags desc='Spoznajte výhody partnerského systému Lovepix, vlastné produkty,veľkoobchodné ceny, ktoré sa vám po prihlásení automaticky zobrazia v eshope'/>
      
      <header>
        <ResponsiveAppBar />
      </header>

      <main className={styles.main}>
        <CustomForPartners />
      </main>

      <footer>
        <FooterLayout />
      </footer>
    </div>
  )
}

export default ForPartners

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale ?? 'sk', ['common'])),
    },
  }
}
