import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import ResponsiveAppBar from "../src/app-bar/responsive-app-bar";
import { GetStaticProps } from "next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import FooterLayout from "../src/screens-content/footer/footer";
import GalleryLayout from "../src/screens-content/gallery/gallery";
import MetaTags from "meta-tags/meta";

const Gallery: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Gallery</title>
        <meta name="Gallery" content="Generated by create next app" />
      </Head>

      {/* MetaTags has to be executed outside of head*/}
      <MetaTags desc='Zháňate moderné obrazy do bytu, domu alebo kancelárie? Máme pre Vás tie najkrajšie, paličkovaná čipka či tlačený obraz - široký výber motívov za výrobné ceny. Produkty expedujeme do 3 dní.'/>

      <header>
        <ResponsiveAppBar />
      </header>

      <main className={styles.main}>
        <GalleryLayout />
      </main>

      <footer>
        <FooterLayout />
      </footer>
    </div>
  );
};

export default Gallery;

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale ?? "sk", ["common"])),
    },
  };
};
