import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import ResponsiveAppBar from '../src/app-bar/responsive-app-bar'
import { Container } from '@mui/material'
import CustomMaterials from '../src/screens-content/materials/materials'
import { GetStaticProps } from 'next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import FooterLayout from "../src/screens-content/footer/footer";
import MetaTags from 'meta-tags/meta'

const Materials: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Materials</title>
        <meta name='Materials' content='Generated by create next app' />
      </Head>

      {/* MetaTags has to be executed outside of head*/}
      <MetaTags desc='Plátno pôsobí veľmi decentne a teplo. Má jemnú štruktúru a je ideálne napnuté. Tlačený motív pokračuje aj po hranách obrazu. Na zavesenie sú na zadnej strane pripravené malé háčiky. Hodí sa najmä do moderných interiérov. Hodnotu obrazu dodá aj spôsob zavesenia. Buď môžete použiť háčiky alebo hlinikové dištančné stĺpiky, ktoré obraz odsadia 3 cm od steny. Alucobond Je to sendvičový materiál, ktorý sa skladá z troch vrstiev hliník – plast – hliník o hrúbke 3mm. Tento materiál je veľmi pevný a trvácny, vhodný aj na exteriérové použitie. Potlačená plocha má úplne jemnú, matnú štruktúru a pôsobí veľmi príjemne. Tak ako pri akryle, aj tu je viacero možností zavesenia. Buď háčik alebo dištančné stĺpiky.'/>

      <header>
        <ResponsiveAppBar />
      </header>

      <main className={styles.main}>
        <Container>
          <CustomMaterials />
        </Container>
      </main>

      <footer>
        <FooterLayout />
      </footer>
    </div>
  )
}

export default Materials

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale ?? 'sk', ['common'])),
    },
  }
}
