import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import ResponsiveAppBar from '../src/app-bar/responsive-app-bar'
import FooterLayout from "../src/screens-content/footer/footer";
import MetaTags from 'meta-tags/meta';

const Profile: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Profile</title>
        <meta name='profile' content='Generated by create next app' />
        <link rel='icon' href='/favicon/favicon-16x16.png' />
      </Head>

      {/* MetaTags has to be executed outside of head*/}
      <MetaTags/>

      <header>
        <ResponsiveAppBar />
      </header>

      <main className={styles.main}></main>

      <footer>
        <FooterLayout />
      </footer>
    </div>
  )
}

export default Profile
