import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Thank from '../src/screens-content/thanks/thanks'
import { GetStaticProps } from 'next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import MetaTags from 'meta-tags/meta'

const Thanks: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Thanks</title>
        <meta name='Thanks' content='Generated by create next app' />
        <link rel='icon' href='/favicon/favicon-16x16.png' />
      </Head>

      {/* MetaTags has to be executed outside of head*/}
      <MetaTags/>

      <main className={styles.main}>
        <Thank />
      </main>

    </div>
  )
}

export default Thanks

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale ?? 'sk', ['common'])),
    },
  }
}
