export const SUPERFAKTURA_EMAIL = process.env.NEXT_PUBLIC_SUPERFAKTURA_EMAIL!
export const SUPERFAKTURA_API_KEY = process.env.NEXT_PUBLIC_SUPERFAKTURA_API_KEY!
export const SUPERFAKTURA_COMPANY_ID = process.env.NEXT_PUBLIC_SUPERFAKTURA_COMPANY_ID!
export const SUPERFAKTURA_MODULE = process.env.NEXT_PUBLIC_SUPERFAKTURA_MODULE!
export const SUPERFAKTURA_EMAIL_TEST = process.env.NEXT_PUBLIC_SUPERFAKTURA_EMAIL_TEST!
export const SUPERFAKTURA_API_KEY_TEST = process.env.NEXT_PUBLIC_SUPERFAKTURA_API_KEY_TEST!
export const SUPERFAKTURA_COMPANY_ID_TEST = process.env.NEXT_PUBLIC_SUPERFAKTURA_COMPANY_ID_TEST!
export const SUPERFAKTURA_MODULE_TEST = process.env.NEXT_PUBLIC_SUPERFAKTURA_MODULE_TEST!