export const SUPERFAKTURA_EMAIL = process.env.NEXT_PUBLIC_SUPERFAKTURA_CONTACT_EMAIL!
export const SUPERFAKTURA_API_KEY = process.env.NEXT_PUBLIC_SUPERFAKTURA_API_KEY!
export const SUPERFAKTURA_COMPANY_ID = process.env.NEXT_PUBLIC_SUPERFAKTURA_COMPANY_ID!
export const SUPERFAKTURA_MODULE = process.env.NEXT_PUBLIC_SUPERFAKTURA_MODULE!