import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import ResponsiveAppBar from "../src/app-bar/responsive-app-bar";
import useLoggeduser from "custom-hooks/use-logged-user";

const Account: NextPage = () => {
  const { user } = useLoggeduser();

  return (
    <div className={styles.container}>
      <Head>
        <title>Account</title>
        <meta name='account' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <header>
        <ResponsiveAppBar />
      </header>
      {user && (
        <>
          <div>{user?.displayName}</div>
          <div>{user?.email}</div>
          <img src={user?.photoURL || ""} alt='user-image' />
        </>
      )}

      <main className={styles.main}></main>

      <footer className={styles.footer}>Powered by Hashlab s.r.o</footer>
    </div>
  );
};

export default Account;
