import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import ResponsiveAppBar from "../src/app-bar/responsive-app-bar";
import { GetStaticProps } from "next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import CustomForPartners from "../src/screens-content/for-partners/for-partners";

const ForPartners: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>For Partners</title>
        <meta name='For Partners' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <header>
        <ResponsiveAppBar />
      </header>

      <main className={styles.main}>
        <CustomForPartners />
      </main>

      <footer className={styles.footer}>Powered by Hashlab s.r.o</footer>
    </div>
  );
};

export default ForPartners;

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale ?? "sk", ["common"])),
    },
  };
};
