import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ResponsiveAppBar from '../src/app-bar/responsive-app-bar'
import { Container } from '@mui/material'
import MasonryImageList from '../src/masonry-image-list/masonry-image-list'

const Gallery: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Gallery</title>
        <meta name='Gallery' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <header>
        <ResponsiveAppBar />
      </header>

      <main className={styles.main}>
        <Container>
          <MasonryImageList />
        </Container>
      </main>

      <footer className={styles.footer}>Powered by Hashlab s.r.o</footer>
    </div>
  )
}

export default Gallery
