import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import ResponsiveAppBar from '../src/app-bar/responsive-app-bar'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import HomeLayout from '../src/screens-content/home/home'
import { useLiveQuery } from "dexie-react-hooks";
import { configurationsTable } from "../database.config";
import { CONFIGURATION_TABLE_KEY } from "../src/common/indexed-db/hooks/keys";

const Home: NextPage = () => {
  const configuration = useLiveQuery(() => configurationsTable.get(CONFIGURATION_TABLE_KEY), []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Waller</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <header>
        <ResponsiveAppBar />
      </header>

      <main className={styles.main}>
        <HomeLayout configuration={configuration} />
      </main>

      <footer className={styles.footer}>Powered by Hashlab s.r.o</footer>
    </div>
  )
}

export default Home

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale ?? 'sk', ['common'])),
    },
  }
}
