import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import ResponsiveAppBar from "../src/app-bar/responsive-app-bar";
import {Container} from "@mui/material";
import CustomMaterials from "../src/screens-content/materials/materials";

const Materials: NextPage = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Materials</title>
        <meta name="Materials" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <header>
        <ResponsiveAppBar/>
      </header>

      <main className={styles.main}>
        <Container>
          <CustomMaterials />
        </Container>
      </main>

      <footer className={styles.footer}>
        Powered by Hashlab s.r.o
      </footer>
    </div>
  )
}

export default Materials
