import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import ResponsiveAppBar from "../src/app-bar/responsive-app-bar";
import {Container, Grid, Typography} from "@mui/material";
import Image from "next/image";
import { v4 as uuidv4 } from 'uuid';

type Material = {
  title: string;
  subtitle: string;
  description: string;
  illustration: string;
}

const materials: Material[] = [
  {
    title: 'Canvas',
    subtitle: 'The paintings on canvas stretched on a quality wooden frame are the most used.',
    description: 'The canvas looks very decent and warm. It has a fine structure and is ideally taut. The printed motif continues along the edges of the image. Small hooks are ready for hanging on the back.',
    illustration: 'https://picsum.photos/seed/picsum/200/300'
  },
  {
    title: 'Akryl - plexiglass',
    subtitle: 'The paintings have a high gloss, which is suitable for both dark and light motifs.',
    description: 'It is especially suitable for modern interiors. The hanging value also adds value to the image. You can either use hooks or aluminum spacers to offset the picture 3 cm from the wall.',
    illustration: 'https://picsum.photos/seed/picsum/200/300'
  },
  {
    title: 'Aluminium plate',
    subtitle: 'Our specialty is printing directly on aluminum plate.',
    description: 'It is a sandwich material, which consists of three layers of aluminum – plastic – aluminum with a thickness of 3 mm. This material is very strong and durable, also suitable for outdoor use. The printed surface has a completely fine, matte structure and looks very pleasant. As with acrylic, there are several hanging options. Either a hook or spacers.',
    illustration: 'https://picsum.photos/seed/picsum/200/300'
  }
]

const Materials: NextPage = () => {
  const materialComponent = (material: Material, index: number) => {
    const direction = index % 2 ? "row-reverse" : "row"
    const align = index % 2 ? "flex-end" : "flex-start"
    const textAlign = index % 2 ? "right" :  "left"

    return <Grid key={uuidv4()} sx={{my: 8}} container rowSpacing={4} columnSpacing={4} direction={direction}>
      <Grid item xs={12} md={3}>
        <Image
          alt={material.title}
          style={{ borderRadius: 10 }}
          key={material.illustration}
          src={material.illustration}
          height={200}
          width={200}
          layout="responsive"
          objectFit="cover"
        />
      </Grid>
      <Grid item xs={12} md={9}>
        <Grid container direction="column" rowSpacing={2} alignItems={align}>
          <Grid item>
            <Typography variant="h5" fontWeight="bold" textAlign={textAlign}>{material.title}</Typography>
          </Grid>
          <Grid item>
            <Typography textAlign={textAlign}>{material.subtitle}</Typography>
          </Grid>
          <Grid item>
            <Typography textAlign={textAlign}>{material.description}</Typography>
          </Grid>
        </Grid>
      </Grid>
    </Grid>
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Materials</title>
        <meta name="Materials" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <header>
        <ResponsiveAppBar/>
      </header>

      <main className={styles.main}>
        <Container>
          {materials.map(materialComponent)}
        </Container>
      </main>

      <footer className={styles.footer}>
        Powered by Hashlab s.r.o
      </footer>
    </div>
  )
}

export default Materials
