import type {NextPage} from 'next'
import {GetStaticProps} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import ResponsiveAppBar from '../src/app-bar/responsive-app-bar'
import {serverSideTranslations} from 'next-i18next/serverSideTranslations'
import FooterLayout from "../src/screens-content/footer/footer";

const OurStory: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>About us</title>
        <meta name='Nas-Pribeh' content='Generated by create next app'/>
        <link rel='icon' href='/favicon.ico'/>
      </Head>

      <header>
        <ResponsiveAppBar/>
      </header>

      <main className={styles.main}>
      </main>

      <footer>
        <FooterLayout/>
      </footer>
    </div>
  )
}

export default OurStory

export const getStaticProps: GetStaticProps = async ({locale}) => {
  return {
    props: {
      ...(await serverSideTranslations(locale ?? 'sk', ['common'])),
    },
  }
}
