export const GALLERY = 'Gallery'
export const MATERIALS = 'Materials'
export const ABOUT_US = 'About us'
export const FOR_PARTNERS = 'For partners'
export const CONFIGURATOR = 'Image configurator'
export const ESHOP = 'E-shop'
export const THANKS = 'Thanks'
export const CONTACT = 'Contact'
