export const GALLERY = 'Gallery'
export const MATERIALS = 'Materials'
export const ABOUT_US = 'About us'
export const FOR_PARTNERS = 'For partners'
export const CONFIGURATOR = 'Image configurator'
export const ESHOP = 'E-shop'
export const THANKS = 'Thanks'
export const CONTACT = 'Contact'
export const DOWNLOAD = 'Download'
export const BLOG = 'Blog'
export const SATISFACTION = 'Satisfaction'
export const POSSIBILITIES = 'Possibilities'
export const PRODUCTION_TIME = 'Production time'
export const COMPLAINT = 'Complaint'

export const PROFILE = 'Profile'
