export enum Pages {
  HOME = '/',
  GALLERY = '/gallery',
  MATERIALS = '/materials',
  ABOUT_US = '/about-us',
  FOR_PARTNERS = '/for-partners',
  SHOPPING_CART = '/shopping-cart',
  CONFIGURATOR = '/configurator',
  ESHOP = '/e-shop',
  THANKS = '/thanks',
  COOKIES = '/cookies',
  GENERAL_TERMS_AND_CONDITIONS = '/general-terms-and-conditions',
  PERSONAL_DATA_PROTECTION_PRINCIPLES = '/personal-data-protection-principles',
  CONTACT = '/contact',
  PROFILE = '/profile',
  ACCOUNT = '/account',
  REVIEWS = '/reviews',
  BLOG = '/blog',
  PRODUCTION_TIME = '/production-time',
  DASHBOARD = '/dashboard',
  DEBUG = '/debug',
  ACRYLIC_PHOTO = '/acrylic-photo',
  COMPLAINTS_AND_RETURNS = '/complaints-and-returns',
  DELIVERY_OPTIONS_AND_PRICES = '/delivery-options-and-prices',
  FOR_DOWNLOAD = '/for-download',
  ORDER_AND_PAYMENT_OPTIONS = '/order-and-payment-options',
  OUR_STORY = '/our-story',
  PHOTO_ON_CANVAS = '/photo-on-canvas',
  POSTER_PHOTO = '/poster-photo',
  PRICING = '/pricing',
  SATISFACTION_GUARANTEE = '/satisfaction-guarantee',
}

export const FACEBOOK = 'https://www.facebook.com/lovepix.sk/'
export const INSTAGRAM = 'https://www.instagram.com/lovepix.eu/'
