name: Deploy to Firebase - TEST ENV Firebase env

on:
  workflow_dispatch:
  push:
    tags:
      - release_*
    branches:
      - test

defaults:
  run:
    working-directory: ./frontend 
env:
  FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
  NPM_GITHUB_TOKEN: ${{secrets.NPM_GITHUB_TOKEN}}
  NEXT_PUBLIC_SMART_EMAILING_HOST: ${{secrets.NEXT_PUBLIC_SMART_EMAILING_HOST}}
  NEXT_PUBLIC_SMART_EMAILING_TOKEN: ${{secrets.NEXT_PUBLIC_SMART_EMAILING_TOKEN}}
  NEXT_PUBLIC_SMART_EMAILING_CONTACT_LIST_ID: ${{secrets.NEXT_PUBLIC_SMART_EMAILING_CONTACT_LIST_ID}}
  NEXT_PUBLIC_SUPERFAKTURA_EMAIL: ${{secrets.NEXT_PUBLIC_SUPERFAKTURA_EMAIL}}
  NEXT_PUBLIC_SUPERFAKTURA_API_KEY: ${{secrets.NEXT_PUBLIC_SUPERFAKTURA_API_KEY}}
  NEXT_PUBLIC_SUPERFAKTURA_COMPANY_ID: ${{secrets.NEXT_PUBLIC_SUPERFAKTURA_COMPANY_ID}}
  NEXT_PUBLIC_SUPERFAKTURA_MODULE: ${{secrets.NEXT_PUBLIC_SUPERFAKTURA_MODULE}}
  NEXT_PUBLIC_STRIPE_PUBLIC_KEY: ${{secrets.NEXT_PUBLIC_STRIPE_PUBLIC_KEY}}
  NEXT_PUBLIC_STRIPE_SECRET_KEY: ${{secrets.NEXT_PUBLIC_STRIPE_SECRET_KEY}}
  NEXT_PUBLIC_NODE_MAILER_SERVICE: ${{secrets.NEXT_PUBLIC_NODE_MAILER_SERVICE}}
  NEXT_PUBLIC_NODE_MAILER_HOST: ${{secrets.NEXT_PUBLIC_NODE_MAILER_HOST}}
  NEXT_PUBLIC_NODE_MAILER_SECURE: ${{secrets.NEXT_PUBLIC_NODE_MAILER_SECURE}}
  NEXT_PUBLIC_NODE_MAILER_PORT: ${{secrets.NEXT_PUBLIC_NODE_MAILER_PORT}}
  NEXT_PUBLIC_NODE_MAILER_USER: ${{secrets.NEXT_PUBLIC_NODE_MAILER_USER}}
  NEXT_PUBLIC_NODE_MAILER_PASSWORD: ${{secrets.NEXT_PUBLIC_NODE_MAILER_PASSWORD}}
  NEXT_PUBLIC_NODE_FIREBASE_API_KEY: ${{secrets.NEXT_PUBLIC_NODE_FIREBASE_API_KEY}}
  NEXT_PUBLIC_NODE_FIREBASE_AUTH_DOMAIN: ${{secrets.NEXT_PUBLIC_NODE_FIREBASE_AUTH_DOMAIN}}
  NEXT_PUBLIC_NODE_FIREBASE_PROJECT_ID: ${{secrets.NEXT_PUBLIC_NODE_FIREBASE_PROJECT_ID}}
  NEXT_PUBLIC_NODE_FIREBASE_STORAGE_BUCKET: ${{secrets.NEXT_PUBLIC_NODE_FIREBASE_STORAGE_BUCKET}}
  NEXT_PUBLIC_NODE_FIREBASE_STORAGE_MESSAGING_SENDER_ID: ${{secrets.NEXT_PUBLIC_NODE_FIREBASE_STORAGE_MESSAGING_SENDER_ID}}
  NEXT_PUBLIC_NODE_FIREBASE_APP_ID: ${{secrets.NEXT_PUBLIC_NODE_FIREBASE_APP_ID}}
  NEXT_PUBLIC_NODE_FIREBASE_MEASUREMENT_ID: ${{secrets.NEXT_PUBLIC_NODE_FIREBASE_MEASUREMENT_ID}}
  FIREBASE_RC_CONTENT: ${{secrets.FIREBASE_RC_CONTENT}}
  NEXT_PUBLIC_GOOGLE_ANALYTICS: ${{secrets.NEXT_PUBLIC_GOOGLE_ANALYTICS}}
  SENTRY_AUTH_TOKEN: ${{secrets.SENTRY_AUTH_TOKEN}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --project ${{ secrets.FIREBASE_PROJECT_ID }} --token ${{ secrets.FIREBASE_TOKEN }}
        env:
          PROJECT_PATH: ./frontend
          FIREBASE_CLI_EXPERIMENTS: webframeworks