name: Deploy to Firebase - TEST ENV

on:
  workflow_dispatch:
  push:
    tags:
      - firebase-deploy_*
    branches:
      - firebase-deploy

defaults:
  run:
    working-directory: ./frontend 
env:
  FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
  NEXT_PUBLIC_NODE_FIREBASE_API_KEY: ${{secrets.NEXT_PUBLIC_NODE_FIREBASE_API_KEY}}
  NEXT_PUBLIC_NODE_FIREBASE_AUTH_DOMAIN: ${{secrets.NEXT_PUBLIC_NODE_FIREBASE_AUTH_DOMAIN}}
  NEXT_PUBLIC_NODE_FIREBASE_PROJECT_ID: ${{secrets.NEXT_PUBLIC_NODE_FIREBASE_PROJECT_ID}}
  NEXT_PUBLIC_NODE_FIREBASE_STORAGE_BUCKET: ${{secrets.NEXT_PUBLIC_NODE_FIREBASE_STORAGE_BUCKET}}
  NEXT_PUBLIC_NODE_FIREBASE_STORAGE_MESSAGING_SENDER_ID: ${{secrets.NEXT_PUBLIC_NODE_FIREBASE_STORAGE_MESSAGING_SENDER_ID}}
  NEXT_PUBLIC_NODE_FIREBASE_APP_ID: ${{secrets.NEXT_PUBLIC_NODE_FIREBASE_APP_ID}}
  NEXT_PUBLIC_NODE_FIREBASE_MEASUREMENT_ID: ${{secrets.NEXT_PUBLIC_NODE_FIREBASE_MEASUREMENT_ID}}


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: $FIREBASE_TOKEN
          PROJECT_PATH: ./frontend
          FIREBASE_CLI_EXPERIMENTS: webframeworks