name: Data migration from Firebase to Mongo DB - Lovepix
on:
  workflow_dispatch:
    inputs:
      collections:
        description: "Which collections you want migrate?
        admins
        categories-eshop
        categories
        contents
        dimensions
        gallery
        "
        type: "string"

jobs:
  migrate-to-mongodb:
    runs-on: ubuntu-latest
    steps:
      - name: deploying on ec2 and rebuild docker-compose with nginX
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.NEW_ORG_AWS_TEST_HOST }}
          username: ec2-user
          key: ${{ secrets.NEW_ORG_AWS_TEST_PEM }}
          port: 22
          script: |
            cd docker-nginx-letsencrypt-https-ec2/backup_data_firebase/output_python
            sh export-data-from-firebase-${{inputs.collections}}.sh
