name: LOVEPIX DockerHub Deployment on ORGANIZATION K8s PROD environment - FRONTEND
# on: [push] # - only for test
on:
  workflow_dispatch:

  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./frontend  

env:
  DOCKER_HUB_USER: ${{secrets.DOCKER_HUB_USERNAME}}
  DOCKER_HUB_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
  DOCKER_TAG_WALLER_FE: ${{secrets.DOCKER_TAG_WALLER_FE}}
  NEXT_PUBLIC_SMART_EMAILING_HOST: ${{secrets.NEXT_PUBLIC_SMART_EMAILING_HOST}}
  NEXT_PUBLIC_SMART_EMAILING_TOKEN: ${{secrets.NEXT_PUBLIC_SMART_EMAILING_TOKEN}}
  NEXT_PUBLIC_SMART_EMAILING_CONTACT_LIST_ID: ${{secrets.NEXT_PUBLIC_SMART_EMAILING_CONTACT_LIST_ID}}
  NEXT_PUBLIC_SUPERFAKTURA_EMAIL: ${{secrets.NEXT_PUBLIC_SUPERFAKTURA_EMAIL}}
  NEXT_PUBLIC_SUPERFAKTURA_API_KEY: ${{secrets.NEXT_PUBLIC_SUPERFAKTURA_API_KEY}}
  NEXT_PUBLIC_SUPERFAKTURA_COMPANY_ID: ${{secrets.NEXT_PUBLIC_SUPERFAKTURA_COMPANY_ID}}
  NEXT_PUBLIC_SUPERFAKTURA_MODULE: ${{secrets.NEXT_PUBLIC_SUPERFAKTURA_MODULE}}
  NEXT_PUBLIC_STRIPE_PUBLIC_KEY: ${{secrets.NEXT_PUBLIC_STRIPE_PUBLIC_KEY}}
  NEXT_PUBLIC_STRIPE_SECRET_KEY: ${{secrets.NEXT_PUBLIC_STRIPE_SECRET_KEY}}

jobs:
  push-lovepix-image-on-dockerhub:  
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build docker LOVEPIX frontend image
        run: time DOCKER_BUILDKIT=1 docker build -t waller-fe:latest --build-arg NEXT_PUBLIC_SMART_EMAILING_HOST --build-arg NEXT_PUBLIC_SMART_EMAILING_TOKEN --build-arg NEXT_PUBLIC_SMART_EMAILING_CONTACT_LIST_ID --build-arg NEXT_PUBLIC_SUPERFAKTURA_EMAIL --build-arg NEXT_PUBLIC_SUPERFAKTURA_API_KEY --build-arg NEXT_PUBLIC_SUPERFAKTURA_COMPANY_ID --build-arg NEXT_PUBLIC_SUPERFAKTURA_MODULE --build-arg NEXT_PUBLIC_STRIPE_PUBLIC_KEY --build-arg NEXT_PUBLIC_STRIPE_SECRET_KEY .
      - name: Docker images 
        run: docker images
      - name: Tag the image of WALLER-fe
        run: docker tag waller-fe:latest $DOCKER_HUB_USER/$DOCKER_TAG_WALLER_FE
      - name: Docker images 
        run: docker images
      - name: DOCKER LOGIN
        run: | 
          docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD  
      - name: Docker Push of WALLER-fe image
        run: docker push $DOCKER_HUB_USER/$DOCKER_TAG_WALLER_FE

  deploy:
    name: Deploy on EC2 and on Workers Node Kubernetes - LOVEPIX
    needs: push-lovepix-image-on-dockerhub
    runs-on: ubuntu-latest
    steps:
    - name: deploying on ec2 and rebuild kubernetes pods
      uses: appleboy/ssh-action@v0.1.7
      with:
        envs: DOCKER_HUB_USER, DOCKER_HUB_PASSWORD, DOCKER_TAG_WALLER_FE
        host: ${{ secrets.ORG_AWS_WALLER_PROD_HOST }}
        username: ec2-user
        key: ${{ secrets.ORG_AWS_WALLER_PROD_PEM }}
        port: 22
        script: |
           cd docker-nginx-letsencrypt-https-ec2
           kubectl get pods -n staging
           docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
           docker rmi $DOCKER_HUB_USER/$DOCKER_TAG_WALLER_FE
           docker pull $DOCKER_HUB_USER/$DOCKER_TAG_WALLER_FE
           kubectl delete deployments lovepix -n staging
           kubectl apply -f k8s_lovepix/frontend/stage.yaml

