name: WALLER DockerHub Deployment on ORGANIZATION PROD environment - FRONTEND
on: [push] # - only for testing
#on:
#  workflow_dispatch:
#
#  push:
#    branches:
#      - main

env:
  DOCKER_HUB_USER: ${{secrets.DOCKER_HUB_USERNAME}}
  DOCKER_HUB_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
  DOCKER_TAG_WALLER_FE: ${{secrets.DOCKER_TAG_WALLER_FE}}


jobs:
  push-waller-image-on-dockerhub:  
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        #env:
      - name: Build docker WALLER frontend image
        #env:
        run: docker-compose up -d
      - name: Docker images 
        run: docker images
      - name: Tag the image of WALLER-fe
        run: docker tag waller-fe:latest $DOCKER_HUB_USER/$DOCKER_TAG_WALLER_FE
      - name: Docker images 
        run: docker images
      - name: DOCKER LOGIN
        run: | 
          docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD  
      - name: Docker Push of WALLER-fe image
        run: docker push $DOCKER_HUB_USER/$DOCKER_TAG_WALLER_FE
