name: LOVEPIX DockerHub Deployment on ORGANIZATION K8s TEST environment - FRONTEND
on:
  workflow_dispatch:
  push:
    tags:
      - release_*
    branches:
      - test

defaults:
  run:
    working-directory: ./frontend  

env:
  NPM_GITHUB_TOKEN: ${{secrets.NPM_GITHUB_TOKEN}}
  DOCKER_HUB_USER: ${{secrets.DOCKER_HUB_USERNAME}}
  DOCKER_HUB_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
  DOCKER_TAG_WALLER_FE: ${{secrets.DOCKER_TAG_WALLER_FE}}
  NEXT_PUBLIC_SMART_EMAILING_HOST: ${{secrets.NEXT_PUBLIC_SMART_EMAILING_HOST}}
  NEXT_PUBLIC_SMART_EMAILING_TOKEN: ${{secrets.NEXT_PUBLIC_SMART_EMAILING_TOKEN}}
  NEXT_PUBLIC_SMART_EMAILING_CONTACT_LIST_ID: ${{secrets.NEXT_PUBLIC_SMART_EMAILING_CONTACT_LIST_ID}}
  NEXT_PUBLIC_SUPERFAKTURA_EMAIL: ${{secrets.NEXT_PUBLIC_SUPERFAKTURA_EMAIL}}
  NEXT_PUBLIC_SUPERFAKTURA_API_KEY: ${{secrets.NEXT_PUBLIC_SUPERFAKTURA_API_KEY}}
  NEXT_PUBLIC_SUPERFAKTURA_COMPANY_ID: ${{secrets.NEXT_PUBLIC_SUPERFAKTURA_COMPANY_ID}}
  NEXT_PUBLIC_SUPERFAKTURA_MODULE: ${{secrets.NEXT_PUBLIC_SUPERFAKTURA_MODULE}}
  NEXT_PUBLIC_STRIPE_PUBLIC_KEY: ${{secrets.NEXT_PUBLIC_STRIPE_PUBLIC_KEY}}
  NEXT_PUBLIC_STRIPE_SECRET_KEY: ${{secrets.NEXT_PUBLIC_STRIPE_SECRET_KEY}}
  NEXT_PUBLIC_NODE_MAILER_SERVICE: ${{secrets.NEXT_PUBLIC_NODE_MAILER_SERVICE}}
  NEXT_PUBLIC_NODE_MAILER_HOST: ${{secrets.NEXT_PUBLIC_NODE_MAILER_HOST}}
  NEXT_PUBLIC_NODE_MAILER_SECURE: ${{secrets.NEXT_PUBLIC_NODE_MAILER_SECURE}}
  NEXT_PUBLIC_NODE_MAILER_PORT: ${{secrets.NEXT_PUBLIC_NODE_MAILER_PORT}}
  NEXT_PUBLIC_NODE_MAILER_USER: ${{secrets.NEXT_PUBLIC_NODE_MAILER_USER}}
  NEXT_PUBLIC_NODE_MAILER_PASSWORD: ${{secrets.NEXT_PUBLIC_NODE_MAILER_PASSWORD}}
  NEXT_PUBLIC_NODE_FIREBASE_API_KEY: ${{secrets.NEXT_PUBLIC_NODE_FIREBASE_API_KEY}}
  NEXT_PUBLIC_NODE_FIREBASE_AUTH_DOMAIN: ${{secrets.NEXT_PUBLIC_NODE_FIREBASE_AUTH_DOMAIN}}
  NEXT_PUBLIC_NODE_FIREBASE_PROJECT_ID: ${{secrets.NEXT_PUBLIC_NODE_FIREBASE_PROJECT_ID}}
  NEXT_PUBLIC_NODE_FIREBASE_STORAGE_BUCKET: ${{secrets.NEXT_PUBLIC_NODE_FIREBASE_STORAGE_BUCKET}}
  NEXT_PUBLIC_NODE_FIREBASE_STORAGE_MESSAGING_SENDER_ID: ${{secrets.NEXT_PUBLIC_NODE_FIREBASE_STORAGE_MESSAGING_SENDER_ID}}
  NEXT_PUBLIC_NODE_FIREBASE_APP_ID: ${{secrets.NEXT_PUBLIC_NODE_FIREBASE_APP_ID}}
  NEXT_PUBLIC_NODE_FIREBASE_MEASUREMENT_ID: ${{secrets.NEXT_PUBLIC_NODE_FIREBASE_MEASUREMENT_ID}}
  FIREBASE_RC_CONTENT: ${{secrets.FIREBASE_RC_CONTENT}}
  NEXT_PUBLIC_GOOGLE_ANALYTICS: ${{secrets.NEXT_PUBLIC_GOOGLE_ANALYTICS}}
  SENTRY_AUTH_TOKEN: ${{secrets.SENTRY_AUTH_TOKEN}}

jobs:
  push-lovepix-image-on-dockerhub:  
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build docker LOVEPIX frontend test image
        run: time DOCKER_BUILDKIT=1 docker build -t lovepix-fe:latest --build-arg NPM_GITHUB_TOKEN --build-arg NEXT_PUBLIC_GOOGLE_ANALYTICS --build-arg FIREBASE_RC_CONTENT --build-arg NEXT_PUBLIC_NODE_FIREBASE_MEASUREMENT_ID --build-arg NEXT_PUBLIC_NODE_FIREBASE_APP_ID --build-arg NEXT_PUBLIC_NODE_FIREBASE_STORAGE_MESSAGING_SENDER_ID --build-arg NEXT_PUBLIC_NODE_FIREBASE_STORAGE_BUCKET --build-arg NEXT_PUBLIC_NODE_FIREBASE_PROJECT_ID --build-arg NEXT_PUBLIC_NODE_FIREBASE_AUTH_DOMAIN --build-arg NEXT_PUBLIC_NODE_FIREBASE_API_KEY --build-arg NEXT_PUBLIC_SMART_EMAILING_HOST --build-arg NEXT_PUBLIC_SMART_EMAILING_TOKEN --build-arg NEXT_PUBLIC_SMART_EMAILING_CONTACT_LIST_ID --build-arg NEXT_PUBLIC_SUPERFAKTURA_EMAIL --build-arg NEXT_PUBLIC_SUPERFAKTURA_API_KEY --build-arg NEXT_PUBLIC_SUPERFAKTURA_COMPANY_ID --build-arg NEXT_PUBLIC_SUPERFAKTURA_MODULE --build-arg NEXT_PUBLIC_STRIPE_PUBLIC_KEY --build-arg NEXT_PUBLIC_STRIPE_SECRET_KEY --build-arg NEXT_PUBLIC_NODE_MAILER_SERVICE --build-arg NEXT_PUBLIC_NODE_MAILER_HOST --build-arg NEXT_PUBLIC_NODE_MAILER_SECURE --build-arg NEXT_PUBLIC_NODE_MAILER_PORT --build-arg NEXT_PUBLIC_NODE_MAILER_USER --build-arg NEXT_PUBLIC_NODE_MAILER_PASSWORD --build-arg SENTRY_AUTH_TOKEN .
      - name: Docker images 
        run: docker images
      - name: Tag the image of LOVEPIX-fe
        run: docker tag lovepix-fe:latest $DOCKER_HUB_USER/$DOCKER_TAG_WALLER_FE
      - name: Docker images 
        run: docker images
      - name: DOCKER LOGIN
        run: | 
          docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD  
      - name: Docker Push of LOVEPIX-fe image
        run: docker push $DOCKER_HUB_USER/$DOCKER_TAG_WALLER_FE

  deploy:
    name: Deploy on EC2 and on Workers Node TEST Kubernetes - LOVEPIX
    needs: push-lovepix-image-on-dockerhub
    runs-on: ubuntu-latest
    environment: Test
    steps:
    - name: deploying on ec2 and rebuild TEST kubernetes pods
      uses: appleboy/ssh-action@v0.1.7
      with:
        envs: DOCKER_HUB_USER, DOCKER_HUB_PASSWORD, DOCKER_TAG_WALLER_FE
        host: ${{ secrets.NEW_ORG_AWS_TEST_HOST }}
        username: ec2-user
        key: ${{ secrets.NEW_ORG_AWS_TEST_PEM }}
        port: 22
        script: |
           cd docker-nginx-letsencrypt-https-ec2
           kubectl get pods -n staging
           docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
           docker rmi $DOCKER_HUB_USER/$DOCKER_TAG_WALLER_FE
           docker pull $DOCKER_HUB_USER/$DOCKER_TAG_WALLER_FE
           kubectl delete statefulset lovepix-frontend -n staging
           kubectl apply -f k8s_lovepix/frontend/stage.yaml
