name: LOVEPIX DockerHub Deployment on ORGANIZATION TEST environment - BACKEND
on: [push] # - only for test
# on:
#   workflow_dispatch:

#   push:
#     branches: 
#       - test

defaults:
  run:
    working-directory: ./backend

env:
  DOCKER_HUB_USER: ${{secrets.DOCKER_HUB_USERNAME}}
  DOCKER_HUB_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
  DOCKER_TAG_WALLER_FE: ${{secrets.DOCKER_TAG_WALLER_BE}}
  MONGO_INITDB_ROOT_USERNAME: ${{secrets.MONGO_INITDB_ROOT_USERNAME}}
  MONGO_INITDB_ROOT_PASSWORD: ${{secrets.MONGO_INITDB_ROOT_PASSWORD}}
  MONGODB_SERVER: ${{secrets.MONGODB_SERVER}}
  MONGODB_ENABLE_ADMIN: ${{secrets.MONGODB_ENABLE_ADMIN}}
  MONGODB_ADMINUSERNAME: ${{secrets.MONGODB_ADMINUSERNAME}}
  MONGODB_ADMINPASSWORD: ${{secrets.MONGODB_ADMINPASSWORD}}
  MONGODB_BASICAUTH_USERNAME: ${{secrets.MONGODB_BASICAUTH_USERNAME}}
  MONGODB_BASICAUTH_PASSWORD: ${{secrets.MONGODB_BASICAUTH_PASSWORD}}
  MONGO_URL: ${{secrets.MONGO_URL}}
  MONGO_REPLICA_HOST: ${{secrets.MONGO_REPLICA_HOST}}
  MONGO_REPLICA_PORT: ${{secrets.MONGO_REPLICA_PORT}}
  
jobs:
  push-lovepix-image-on-dockerhub:  
    runs-on: ubuntu-latest 
    environment: Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build docker LOVEPIX backend image
        run: time DOCKER_BUILDKIT=1 docker build -t lovepix-be:latest --build-arg MONGO_INITDB_ROOT_USERNAME --build-arg MONGO_INITDB_ROOT_PASSWORD --build-arg MONGODB_SERVER --build-arg MONGODB_ENABLE_ADMIN --build-arg MONGODB_ADMINUSERNAME --build-arg MONGODB_ADMINPASSWORD --build-arg MONGODB_BASICAUTH_USERNAME --build-arg MONGODB_BASICAUTH_PASSWORD --build-arg MONGO_URL --build-arg MONGO_REPLICA_HOST --build-arg MONGO_REPLICA_PORT .
      - name: Docker images 
        run: docker images
      - name: Tag the image of LOVEPIX-be
        run: docker tag lovepix-be:latest $DOCKER_HUB_USER/$DOCKER_TAG_WALLER_FE
      - name: Docker images 
        run: docker images
      - name: DOCKER LOGIN
        run: | 
          docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD  
      - name: Docker Push of LOVEPIX-be image
        run: docker push $DOCKER_HUB_USER/$DOCKER_TAG_WALLER_FE